version: 2
updates:
  - package-ecosystem: 'nuget'
    directories:
      - 'stage/dotnet/dotnet-sdk'
      - 'stage/dotnet/dotnet-sdk-enterprise-cloud'
      - 'stage/dotnet/dotnet-sdk-enterprise-server'
    schedule:
      interval: 'daily'
    ignore:
      - dependency-name: 'Microsoft.Kiota.*'
    groups:
      test:
        patterns:
          - 'xunit*'
          - 'coverlet*'
      microsoft:
        patterns:
          - 'Microsoft.*'
  - package-ecosystem: 'gomod'
    directories:
      - 'stage/go/go-sdk'
      - 'stage/go/go-sdk-enterprise-cloud'
      - 'stage/go/go-sdk-enterprise-server'
    schedule:
      interval: 'daily'
    ignore:
      - dependency-name: 'github.com/microsoft/kiota*'
  - package-ecosystem: 'github-actions'
    directories:
      - '.github/workflows'
      - 'stage/dotnet/dotnet-sdk/.github/workflows'
      - 'stage/dotnet/dotnet-sdk-enterprise-cloud/.github/workflows'
      - 'stage/dotnet/dotnet-sdk-enterprise-server.github/workflows'
      - 'stage/go/go-sdk/.github/workflows'
      - 'stage/go/go-sdk-enterprise-cloud/.github/workflows'
      - 'stage/go/go-sdk-enterprise-server/.github/workflows'
    schedule:
      interval: 'daily'
