name: "Build and validate Go generated SDK"

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/setup-go@v3.5.0
        with:
          go-version: '1.20'

      - name: Run generation
        run: |
          time autorest autorest-config.yaml --go --debug --verbose
