name: "Build and validate Go generated SDK"

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: '7.x.x'

      - uses: actions/setup-go@v3.5.0
        with:
          go-version: '1.20.4'

      - name: Install kiota
        run: dotnet tool install --global Microsoft.OpenApi.Kiota --version 1.1.3

      - name: Download latest schema
        run: go run schemas/main.go

      - name: Run generation
        run: time kiota generate -l go --ll trace -o generated/go -n kiota -d schemas/downloaded.json --co

      - name: Build post-processing
        run: go build -o post-processors/go/post-processor post-processors/go/main.go

      - name: Run post-processing
        run: post-processors/go/post-processor $(pwd)/generated/go

      - name: Build generated and processed SDK
        run: |
          cd generated/go
          go build ./...
